// Generated by gencpp from file fremen/EstimateOctomapRequest.msg
// DO NOT EDIT!


#ifndef FREMEN_MESSAGE_ESTIMATEOCTOMAPREQUEST_H
#define FREMEN_MESSAGE_ESTIMATEOCTOMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fremen
{
template <class ContainerAllocator>
struct EstimateOctomapRequest_
{
  typedef EstimateOctomapRequest_<ContainerAllocator> Type;

  EstimateOctomapRequest_()
    : mapname()
    , stamp(0.0)
    , minProbability(0.0)
    , maxProbability(0.0)
    , morphology(0)  {
    }
  EstimateOctomapRequest_(const ContainerAllocator& _alloc)
    : mapname(_alloc)
    , stamp(0.0)
    , minProbability(0.0)
    , maxProbability(0.0)
    , morphology(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mapname_type;
  _mapname_type mapname;

   typedef double _stamp_type;
  _stamp_type stamp;

   typedef double _minProbability_type;
  _minProbability_type minProbability;

   typedef double _maxProbability_type;
  _maxProbability_type maxProbability;

   typedef int8_t _morphology_type;
  _morphology_type morphology;





  typedef boost::shared_ptr< ::fremen::EstimateOctomapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fremen::EstimateOctomapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EstimateOctomapRequest_

typedef ::fremen::EstimateOctomapRequest_<std::allocator<void> > EstimateOctomapRequest;

typedef boost::shared_ptr< ::fremen::EstimateOctomapRequest > EstimateOctomapRequestPtr;
typedef boost::shared_ptr< ::fremen::EstimateOctomapRequest const> EstimateOctomapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fremen::EstimateOctomapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fremen::EstimateOctomapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fremen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'fremen': ['/home/stass/StassLea_FYP/devel/share/fremen/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fremen::EstimateOctomapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fremen::EstimateOctomapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::EstimateOctomapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::EstimateOctomapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::EstimateOctomapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::EstimateOctomapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fremen::EstimateOctomapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27d066e39da9c57b6401ca771b5d0994";
  }

  static const char* value(const ::fremen::EstimateOctomapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27d066e39da9c57bULL;
  static const uint64_t static_value2 = 0x6401ca771b5d0994ULL;
};

template<class ContainerAllocator>
struct DataType< ::fremen::EstimateOctomapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fremen/EstimateOctomapRequest";
  }

  static const char* value(const ::fremen::EstimateOctomapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fremen::EstimateOctomapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mapname\n\
float64 stamp\n\
float64 minProbability\n\
float64 maxProbability\n\
int8 morphology\n\
";
  }

  static const char* value(const ::fremen::EstimateOctomapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fremen::EstimateOctomapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapname);
      stream.next(m.stamp);
      stream.next(m.minProbability);
      stream.next(m.maxProbability);
      stream.next(m.morphology);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EstimateOctomapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fremen::EstimateOctomapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fremen::EstimateOctomapRequest_<ContainerAllocator>& v)
  {
    s << indent << "mapname: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mapname);
    s << indent << "stamp: ";
    Printer<double>::stream(s, indent + "  ", v.stamp);
    s << indent << "minProbability: ";
    Printer<double>::stream(s, indent + "  ", v.minProbability);
    s << indent << "maxProbability: ";
    Printer<double>::stream(s, indent + "  ", v.maxProbability);
    s << indent << "morphology: ";
    Printer<int8_t>::stream(s, indent + "  ", v.morphology);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREMEN_MESSAGE_ESTIMATEOCTOMAPREQUEST_H
