// Generated by gencpp from file fremen/EvaluateGridRequest.msg
// DO NOT EDIT!


#ifndef FREMEN_MESSAGE_EVALUATEGRIDREQUEST_H
#define FREMEN_MESSAGE_EVALUATEGRIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fremen
{
template <class ContainerAllocator>
struct EvaluateGridRequest_
{
  typedef EvaluateGridRequest_<ContainerAllocator> Type;

  EvaluateGridRequest_()
    : mapname()
    , maxOrder(0)  {
    }
  EvaluateGridRequest_(const ContainerAllocator& _alloc)
    : mapname(_alloc)
    , maxOrder(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mapname_type;
  _mapname_type mapname;

   typedef int32_t _maxOrder_type;
  _maxOrder_type maxOrder;





  typedef boost::shared_ptr< ::fremen::EvaluateGridRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fremen::EvaluateGridRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EvaluateGridRequest_

typedef ::fremen::EvaluateGridRequest_<std::allocator<void> > EvaluateGridRequest;

typedef boost::shared_ptr< ::fremen::EvaluateGridRequest > EvaluateGridRequestPtr;
typedef boost::shared_ptr< ::fremen::EvaluateGridRequest const> EvaluateGridRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fremen::EvaluateGridRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fremen::EvaluateGridRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fremen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'fremen': ['/home/stass/StassLea_FYP/devel/share/fremen/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fremen::EvaluateGridRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fremen::EvaluateGridRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::EvaluateGridRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::EvaluateGridRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::EvaluateGridRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::EvaluateGridRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fremen::EvaluateGridRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a15c307f0f10b9ea632c0efb4a30d10f";
  }

  static const char* value(const ::fremen::EvaluateGridRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa15c307f0f10b9eaULL;
  static const uint64_t static_value2 = 0x632c0efb4a30d10fULL;
};

template<class ContainerAllocator>
struct DataType< ::fremen::EvaluateGridRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fremen/EvaluateGridRequest";
  }

  static const char* value(const ::fremen::EvaluateGridRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fremen::EvaluateGridRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mapname\n\
int32 maxOrder\n\
";
  }

  static const char* value(const ::fremen::EvaluateGridRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fremen::EvaluateGridRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapname);
      stream.next(m.maxOrder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EvaluateGridRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fremen::EvaluateGridRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fremen::EvaluateGridRequest_<ContainerAllocator>& v)
  {
    s << indent << "mapname: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mapname);
    s << indent << "maxOrder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.maxOrder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREMEN_MESSAGE_EVALUATEGRIDREQUEST_H
