// Generated by gencpp from file fremen/froctomapFeedback.msg
// DO NOT EDIT!


#ifndef FREMEN_MESSAGE_FROCTOMAPFEEDBACK_H
#define FREMEN_MESSAGE_FROCTOMAPFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fremen
{
template <class ContainerAllocator>
struct froctomapFeedback_
{
  typedef froctomapFeedback_<ContainerAllocator> Type;

  froctomapFeedback_()
    {
    }
  froctomapFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::fremen::froctomapFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fremen::froctomapFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct froctomapFeedback_

typedef ::fremen::froctomapFeedback_<std::allocator<void> > froctomapFeedback;

typedef boost::shared_ptr< ::fremen::froctomapFeedback > froctomapFeedbackPtr;
typedef boost::shared_ptr< ::fremen::froctomapFeedback const> froctomapFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fremen::froctomapFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fremen::froctomapFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fremen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'fremen': ['/home/stass/StassLea_FYP/devel/share/fremen/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fremen::froctomapFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fremen::froctomapFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::froctomapFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::froctomapFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::froctomapFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::froctomapFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fremen::froctomapFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::fremen::froctomapFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::fremen::froctomapFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fremen/froctomapFeedback";
  }

  static const char* value(const ::fremen::froctomapFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fremen::froctomapFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
\n\
# update 0 0 0 0 0 0 0 \n\
# recover 1 0 0 0 0 0 0\n\
# estimate 1 0 0 0 0.0 1.1 0\n\
# estimate 1 0 0 0 0.0 1.0 0\n\
\n\
\n\
";
  }

  static const char* value(const ::fremen::froctomapFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fremen::froctomapFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct froctomapFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fremen::froctomapFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::fremen::froctomapFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FREMEN_MESSAGE_FROCTOMAPFEEDBACK_H
