// Generated by gencpp from file fremen/froctomapGoal.msg
// DO NOT EDIT!


#ifndef FREMEN_MESSAGE_FROCTOMAPGOAL_H
#define FREMEN_MESSAGE_FROCTOMAPGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fremen
{
template <class ContainerAllocator>
struct froctomapGoal_
{
  typedef froctomapGoal_<ContainerAllocator> Type;

  froctomapGoal_()
    : name_action()
    , mapname()
    , stamp(0.0)
    , order(0)
    , precision(0.0)
    , lossy(false)
    , minprobability(0.0)
    , maxprobability(0.0)
    , morphology(0)
    , filename()  {
    }
  froctomapGoal_(const ContainerAllocator& _alloc)
    : name_action(_alloc)
    , mapname(_alloc)
    , stamp(0.0)
    , order(0)
    , precision(0.0)
    , lossy(false)
    , minprobability(0.0)
    , maxprobability(0.0)
    , morphology(0)
    , filename(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_action_type;
  _name_action_type name_action;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mapname_type;
  _mapname_type mapname;

   typedef double _stamp_type;
  _stamp_type stamp;

   typedef int64_t _order_type;
  _order_type order;

   typedef double _precision_type;
  _precision_type precision;

   typedef uint8_t _lossy_type;
  _lossy_type lossy;

   typedef double _minprobability_type;
  _minprobability_type minprobability;

   typedef double _maxprobability_type;
  _maxprobability_type maxprobability;

   typedef int8_t _morphology_type;
  _morphology_type morphology;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  _filename_type filename;





  typedef boost::shared_ptr< ::fremen::froctomapGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fremen::froctomapGoal_<ContainerAllocator> const> ConstPtr;

}; // struct froctomapGoal_

typedef ::fremen::froctomapGoal_<std::allocator<void> > froctomapGoal;

typedef boost::shared_ptr< ::fremen::froctomapGoal > froctomapGoalPtr;
typedef boost::shared_ptr< ::fremen::froctomapGoal const> froctomapGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fremen::froctomapGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fremen::froctomapGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fremen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'fremen': ['/home/stass/StassLea_FYP/devel/share/fremen/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fremen::froctomapGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fremen::froctomapGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::froctomapGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::froctomapGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::froctomapGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::froctomapGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fremen::froctomapGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d57d9b96da01473a02e5fb72ec45c690";
  }

  static const char* value(const ::fremen::froctomapGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd57d9b96da01473aULL;
  static const uint64_t static_value2 = 0x02e5fb72ec45c690ULL;
};

template<class ContainerAllocator>
struct DataType< ::fremen::froctomapGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fremen/froctomapGoal";
  }

  static const char* value(const ::fremen::froctomapGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fremen::froctomapGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
string name_action 	# update save predict recover_octomap estimate_octomap\n\
string mapname\n\
float64 stamp		# measurement time\n\
int64 order		# 0 - 100\n\
float64 precision	# 0.0 - 1.0\n\
bool lossy\n\
float64 minprobability  # 0.0 - 1.0\n\
float64 maxprobability	# 0.0 - 1.0\n\
int8 morphology \n\
string filename	\n\
";
  }

  static const char* value(const ::fremen::froctomapGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fremen::froctomapGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name_action);
      stream.next(m.mapname);
      stream.next(m.stamp);
      stream.next(m.order);
      stream.next(m.precision);
      stream.next(m.lossy);
      stream.next(m.minprobability);
      stream.next(m.maxprobability);
      stream.next(m.morphology);
      stream.next(m.filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct froctomapGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fremen::froctomapGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fremen::froctomapGoal_<ContainerAllocator>& v)
  {
    s << indent << "name_action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name_action);
    s << indent << "mapname: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mapname);
    s << indent << "stamp: ";
    Printer<double>::stream(s, indent + "  ", v.stamp);
    s << indent << "order: ";
    Printer<int64_t>::stream(s, indent + "  ", v.order);
    s << indent << "precision: ";
    Printer<double>::stream(s, indent + "  ", v.precision);
    s << indent << "lossy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lossy);
    s << indent << "minprobability: ";
    Printer<double>::stream(s, indent + "  ", v.minprobability);
    s << indent << "maxprobability: ";
    Printer<double>::stream(s, indent + "  ", v.maxprobability);
    s << indent << "morphology: ";
    Printer<int8_t>::stream(s, indent + "  ", v.morphology);
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREMEN_MESSAGE_FROCTOMAPGOAL_H
