// Generated by gencpp from file fremen/informationFeedback.msg
// DO NOT EDIT!


#ifndef FREMEN_MESSAGE_INFORMATIONFEEDBACK_H
#define FREMEN_MESSAGE_INFORMATIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fremen
{
template <class ContainerAllocator>
struct informationFeedback_
{
  typedef informationFeedback_<ContainerAllocator> Type;

  informationFeedback_()
    : gain(0.0)  {
    }
  informationFeedback_(const ContainerAllocator& _alloc)
    : gain(0.0)  {
  (void)_alloc;
    }



   typedef double _gain_type;
  _gain_type gain;





  typedef boost::shared_ptr< ::fremen::informationFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fremen::informationFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct informationFeedback_

typedef ::fremen::informationFeedback_<std::allocator<void> > informationFeedback;

typedef boost::shared_ptr< ::fremen::informationFeedback > informationFeedbackPtr;
typedef boost::shared_ptr< ::fremen::informationFeedback const> informationFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fremen::informationFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fremen::informationFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fremen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'fremen': ['/home/stass/StassLea_FYP/devel/share/fremen/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fremen::informationFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fremen::informationFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::informationFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::informationFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::informationFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::informationFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fremen::informationFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d53ba7b6907d06399427297847c2640";
  }

  static const char* value(const ::fremen::informationFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d53ba7b6907d063ULL;
  static const uint64_t static_value2 = 0x99427297847c2640ULL;
};

template<class ContainerAllocator>
struct DataType< ::fremen::informationFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fremen/informationFeedback";
  }

  static const char* value(const ::fremen::informationFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fremen::informationFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
float64 gain\n\
\n\
\n\
";
  }

  static const char* value(const ::fremen::informationFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fremen::informationFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gain);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct informationFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fremen::informationFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fremen::informationFeedback_<ContainerAllocator>& v)
  {
    s << indent << "gain: ";
    Printer<double>::stream(s, indent + "  ", v.gain);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREMEN_MESSAGE_INFORMATIONFEEDBACK_H
