// Generated by gencpp from file fremen/RetrieveOctomap.msg
// DO NOT EDIT!


#ifndef FREMEN_MESSAGE_RETRIEVEOCTOMAP_H
#define FREMEN_MESSAGE_RETRIEVEOCTOMAP_H

#include <ros/service_traits.h>


#include <fremen/RetrieveOctomapRequest.h>
#include <fremen/RetrieveOctomapResponse.h>


namespace fremen
{

struct RetrieveOctomap
{

typedef RetrieveOctomapRequest Request;
typedef RetrieveOctomapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RetrieveOctomap
} // namespace fremen


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fremen::RetrieveOctomap > {
  static const char* value()
  {
    return "c6c457df6363bb6c3daef5518f11f06a";
  }

  static const char* value(const ::fremen::RetrieveOctomap&) { return value(); }
};

template<>
struct DataType< ::fremen::RetrieveOctomap > {
  static const char* value()
  {
    return "fremen/RetrieveOctomap";
  }

  static const char* value(const ::fremen::RetrieveOctomap&) { return value(); }
};


// service_traits::MD5Sum< ::fremen::RetrieveOctomapRequest> should match 
// service_traits::MD5Sum< ::fremen::RetrieveOctomap > 
template<>
struct MD5Sum< ::fremen::RetrieveOctomapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fremen::RetrieveOctomap >::value();
  }
  static const char* value(const ::fremen::RetrieveOctomapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fremen::RetrieveOctomapRequest> should match 
// service_traits::DataType< ::fremen::RetrieveOctomap > 
template<>
struct DataType< ::fremen::RetrieveOctomapRequest>
{
  static const char* value()
  {
    return DataType< ::fremen::RetrieveOctomap >::value();
  }
  static const char* value(const ::fremen::RetrieveOctomapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fremen::RetrieveOctomapResponse> should match 
// service_traits::MD5Sum< ::fremen::RetrieveOctomap > 
template<>
struct MD5Sum< ::fremen::RetrieveOctomapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fremen::RetrieveOctomap >::value();
  }
  static const char* value(const ::fremen::RetrieveOctomapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fremen::RetrieveOctomapResponse> should match 
// service_traits::DataType< ::fremen::RetrieveOctomap > 
template<>
struct DataType< ::fremen::RetrieveOctomapResponse>
{
  static const char* value()
  {
    return DataType< ::fremen::RetrieveOctomap >::value();
  }
  static const char* value(const ::fremen::RetrieveOctomapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FREMEN_MESSAGE_RETRIEVEOCTOMAP_H
