// Generated by gencpp from file fremen/SaveGridResponse.msg
// DO NOT EDIT!


#ifndef FREMEN_MESSAGE_SAVEGRIDRESPONSE_H
#define FREMEN_MESSAGE_SAVEGRIDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fremen
{
template <class ContainerAllocator>
struct SaveGridResponse_
{
  typedef SaveGridResponse_<ContainerAllocator> Type;

  SaveGridResponse_()
    : size(0)
    , result(false)  {
    }
  SaveGridResponse_(const ContainerAllocator& _alloc)
    : size(0)
    , result(false)  {
  (void)_alloc;
    }



   typedef int64_t _size_type;
  _size_type size;

   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::fremen::SaveGridResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fremen::SaveGridResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaveGridResponse_

typedef ::fremen::SaveGridResponse_<std::allocator<void> > SaveGridResponse;

typedef boost::shared_ptr< ::fremen::SaveGridResponse > SaveGridResponsePtr;
typedef boost::shared_ptr< ::fremen::SaveGridResponse const> SaveGridResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fremen::SaveGridResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fremen::SaveGridResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fremen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'fremen': ['/home/stass/StassLea_FYP/devel/share/fremen/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fremen::SaveGridResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fremen::SaveGridResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::SaveGridResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::SaveGridResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::SaveGridResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::SaveGridResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fremen::SaveGridResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4436e3d8eaa438b4c165950dcfa74370";
  }

  static const char* value(const ::fremen::SaveGridResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4436e3d8eaa438b4ULL;
  static const uint64_t static_value2 = 0xc165950dcfa74370ULL;
};

template<class ContainerAllocator>
struct DataType< ::fremen::SaveGridResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fremen/SaveGridResponse";
  }

  static const char* value(const ::fremen::SaveGridResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fremen::SaveGridResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 size\n\
bool result\n\
\n\
";
  }

  static const char* value(const ::fremen::SaveGridResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fremen::SaveGridResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.size);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveGridResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fremen::SaveGridResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fremen::SaveGridResponse_<ContainerAllocator>& v)
  {
    s << indent << "size: ";
    Printer<int64_t>::stream(s, indent + "  ", v.size);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREMEN_MESSAGE_SAVEGRIDRESPONSE_H
