// Generated by gencpp from file fremen/SaveGridRequest.msg
// DO NOT EDIT!


#ifndef FREMEN_MESSAGE_SAVEGRIDREQUEST_H
#define FREMEN_MESSAGE_SAVEGRIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fremen
{
template <class ContainerAllocator>
struct SaveGridRequest_
{
  typedef SaveGridRequest_<ContainerAllocator> Type;

  SaveGridRequest_()
    : mapname()
    , filename()
    , order(0)
    , lossy(false)  {
    }
  SaveGridRequest_(const ContainerAllocator& _alloc)
    : mapname(_alloc)
    , filename(_alloc)
    , order(0)
    , lossy(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mapname_type;
  _mapname_type mapname;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  _filename_type filename;

   typedef int64_t _order_type;
  _order_type order;

   typedef uint8_t _lossy_type;
  _lossy_type lossy;





  typedef boost::shared_ptr< ::fremen::SaveGridRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fremen::SaveGridRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveGridRequest_

typedef ::fremen::SaveGridRequest_<std::allocator<void> > SaveGridRequest;

typedef boost::shared_ptr< ::fremen::SaveGridRequest > SaveGridRequestPtr;
typedef boost::shared_ptr< ::fremen::SaveGridRequest const> SaveGridRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fremen::SaveGridRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fremen::SaveGridRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fremen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'fremen': ['/home/stass/StassLea_FYP/devel/share/fremen/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fremen::SaveGridRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fremen::SaveGridRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::SaveGridRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::SaveGridRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::SaveGridRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::SaveGridRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fremen::SaveGridRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "337d03d51d21a13513f09c8e984e8d9d";
  }

  static const char* value(const ::fremen::SaveGridRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x337d03d51d21a135ULL;
  static const uint64_t static_value2 = 0x13f09c8e984e8d9dULL;
};

template<class ContainerAllocator>
struct DataType< ::fremen::SaveGridRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fremen/SaveGridRequest";
  }

  static const char* value(const ::fremen::SaveGridRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fremen::SaveGridRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mapname\n\
string filename\n\
int64 order\n\
bool lossy\n\
";
  }

  static const char* value(const ::fremen::SaveGridRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fremen::SaveGridRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapname);
      stream.next(m.filename);
      stream.next(m.order);
      stream.next(m.lossy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveGridRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fremen::SaveGridRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fremen::SaveGridRequest_<ContainerAllocator>& v)
  {
    s << indent << "mapname: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mapname);
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filename);
    s << indent << "order: ";
    Printer<int64_t>::stream(s, indent + "  ", v.order);
    s << indent << "lossy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lossy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREMEN_MESSAGE_SAVEGRIDREQUEST_H
