// Generated by gencpp from file fremen/SaveGrid.msg
// DO NOT EDIT!


#ifndef FREMEN_MESSAGE_SAVEGRID_H
#define FREMEN_MESSAGE_SAVEGRID_H

#include <ros/service_traits.h>


#include <fremen/SaveGridRequest.h>
#include <fremen/SaveGridResponse.h>


namespace fremen
{

struct SaveGrid
{

typedef SaveGridRequest Request;
typedef SaveGridResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveGrid
} // namespace fremen


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fremen::SaveGrid > {
  static const char* value()
  {
    return "485ca739c23c103eb4a0dc9cfd558e95";
  }

  static const char* value(const ::fremen::SaveGrid&) { return value(); }
};

template<>
struct DataType< ::fremen::SaveGrid > {
  static const char* value()
  {
    return "fremen/SaveGrid";
  }

  static const char* value(const ::fremen::SaveGrid&) { return value(); }
};


// service_traits::MD5Sum< ::fremen::SaveGridRequest> should match 
// service_traits::MD5Sum< ::fremen::SaveGrid > 
template<>
struct MD5Sum< ::fremen::SaveGridRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fremen::SaveGrid >::value();
  }
  static const char* value(const ::fremen::SaveGridRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fremen::SaveGridRequest> should match 
// service_traits::DataType< ::fremen::SaveGrid > 
template<>
struct DataType< ::fremen::SaveGridRequest>
{
  static const char* value()
  {
    return DataType< ::fremen::SaveGrid >::value();
  }
  static const char* value(const ::fremen::SaveGridRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fremen::SaveGridResponse> should match 
// service_traits::MD5Sum< ::fremen::SaveGrid > 
template<>
struct MD5Sum< ::fremen::SaveGridResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fremen::SaveGrid >::value();
  }
  static const char* value(const ::fremen::SaveGridResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fremen::SaveGridResponse> should match 
// service_traits::DataType< ::fremen::SaveGrid > 
template<>
struct DataType< ::fremen::SaveGridResponse>
{
  static const char* value()
  {
    return DataType< ::fremen::SaveGrid >::value();
  }
  static const char* value(const ::fremen::SaveGridResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FREMEN_MESSAGE_SAVEGRID_H
