// Generated by gencpp from file fremen/UpdateGridResponse.msg
// DO NOT EDIT!


#ifndef FREMEN_MESSAGE_UPDATEGRIDRESPONSE_H
#define FREMEN_MESSAGE_UPDATEGRIDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fremen
{
template <class ContainerAllocator>
struct UpdateGridResponse_
{
  typedef UpdateGridResponse_<ContainerAllocator> Type;

  UpdateGridResponse_()
    : allError(0.0)
    , nonemptyError(0.0)
    , dynamicError(0.0)
    , size(0)
    , result(false)  {
    }
  UpdateGridResponse_(const ContainerAllocator& _alloc)
    : allError(0.0)
    , nonemptyError(0.0)
    , dynamicError(0.0)
    , size(0)
    , result(false)  {
  (void)_alloc;
    }



   typedef float _allError_type;
  _allError_type allError;

   typedef float _nonemptyError_type;
  _nonemptyError_type nonemptyError;

   typedef float _dynamicError_type;
  _dynamicError_type dynamicError;

   typedef int64_t _size_type;
  _size_type size;

   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::fremen::UpdateGridResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fremen::UpdateGridResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateGridResponse_

typedef ::fremen::UpdateGridResponse_<std::allocator<void> > UpdateGridResponse;

typedef boost::shared_ptr< ::fremen::UpdateGridResponse > UpdateGridResponsePtr;
typedef boost::shared_ptr< ::fremen::UpdateGridResponse const> UpdateGridResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fremen::UpdateGridResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fremen::UpdateGridResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fremen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'fremen': ['/home/stass/StassLea_FYP/devel/share/fremen/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fremen::UpdateGridResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fremen::UpdateGridResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::UpdateGridResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremen::UpdateGridResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::UpdateGridResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremen::UpdateGridResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fremen::UpdateGridResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2be2b95dcbfa6dd0565a9eae4ac32d50";
  }

  static const char* value(const ::fremen::UpdateGridResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2be2b95dcbfa6dd0ULL;
  static const uint64_t static_value2 = 0x565a9eae4ac32d50ULL;
};

template<class ContainerAllocator>
struct DataType< ::fremen::UpdateGridResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fremen/UpdateGridResponse";
  }

  static const char* value(const ::fremen::UpdateGridResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fremen::UpdateGridResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 allError\n\
float32 nonemptyError\n\
float32 dynamicError\n\
int64 size\n\
bool result\n\
\n\
";
  }

  static const char* value(const ::fremen::UpdateGridResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fremen::UpdateGridResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.allError);
      stream.next(m.nonemptyError);
      stream.next(m.dynamicError);
      stream.next(m.size);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateGridResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fremen::UpdateGridResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fremen::UpdateGridResponse_<ContainerAllocator>& v)
  {
    s << indent << "allError: ";
    Printer<float>::stream(s, indent + "  ", v.allError);
    s << indent << "nonemptyError: ";
    Printer<float>::stream(s, indent + "  ", v.nonemptyError);
    s << indent << "dynamicError: ";
    Printer<float>::stream(s, indent + "  ", v.dynamicError);
    s << indent << "size: ";
    Printer<int64_t>::stream(s, indent + "  ", v.size);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREMEN_MESSAGE_UPDATEGRIDRESPONSE_H
