// Generated by gencpp from file fremen/UpdateGrid.msg
// DO NOT EDIT!


#ifndef FREMEN_MESSAGE_UPDATEGRID_H
#define FREMEN_MESSAGE_UPDATEGRID_H

#include <ros/service_traits.h>


#include <fremen/UpdateGridRequest.h>
#include <fremen/UpdateGridResponse.h>


namespace fremen
{

struct UpdateGrid
{

typedef UpdateGridRequest Request;
typedef UpdateGridResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateGrid
} // namespace fremen


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fremen::UpdateGrid > {
  static const char* value()
  {
    return "ec761d237f96cedb8fde2a090de101cc";
  }

  static const char* value(const ::fremen::UpdateGrid&) { return value(); }
};

template<>
struct DataType< ::fremen::UpdateGrid > {
  static const char* value()
  {
    return "fremen/UpdateGrid";
  }

  static const char* value(const ::fremen::UpdateGrid&) { return value(); }
};


// service_traits::MD5Sum< ::fremen::UpdateGridRequest> should match 
// service_traits::MD5Sum< ::fremen::UpdateGrid > 
template<>
struct MD5Sum< ::fremen::UpdateGridRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fremen::UpdateGrid >::value();
  }
  static const char* value(const ::fremen::UpdateGridRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fremen::UpdateGridRequest> should match 
// service_traits::DataType< ::fremen::UpdateGrid > 
template<>
struct DataType< ::fremen::UpdateGridRequest>
{
  static const char* value()
  {
    return DataType< ::fremen::UpdateGrid >::value();
  }
  static const char* value(const ::fremen::UpdateGridRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fremen::UpdateGridResponse> should match 
// service_traits::MD5Sum< ::fremen::UpdateGrid > 
template<>
struct MD5Sum< ::fremen::UpdateGridResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fremen::UpdateGrid >::value();
  }
  static const char* value(const ::fremen::UpdateGridResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fremen::UpdateGridResponse> should match 
// service_traits::DataType< ::fremen::UpdateGrid > 
template<>
struct DataType< ::fremen::UpdateGridResponse>
{
  static const char* value()
  {
    return DataType< ::fremen::UpdateGrid >::value();
  }
  static const char* value(const ::fremen::UpdateGridResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FREMEN_MESSAGE_UPDATEGRID_H
