; Auto-generated. Do not edit!


(cl:in-package fremen-msg)


;//! \htmlinclude froctomapFeedback.msg.html

(cl:defclass <froctomapFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass froctomapFeedback (<froctomapFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <froctomapFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'froctomapFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fremen-msg:<froctomapFeedback> is deprecated: use fremen-msg:froctomapFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <froctomapFeedback>) ostream)
  "Serializes a message object of type '<froctomapFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <froctomapFeedback>) istream)
  "Deserializes a message object of type '<froctomapFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<froctomapFeedback>)))
  "Returns string type for a message object of type '<froctomapFeedback>"
  "fremen/froctomapFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'froctomapFeedback)))
  "Returns string type for a message object of type 'froctomapFeedback"
  "fremen/froctomapFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<froctomapFeedback>)))
  "Returns md5sum for a message object of type '<froctomapFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'froctomapFeedback)))
  "Returns md5sum for a message object of type 'froctomapFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<froctomapFeedback>)))
  "Returns full string definition for message of type '<froctomapFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%# update 0 0 0 0 0 0 0 ~%# recover 1 0 0 0 0 0 0~%# estimate 1 0 0 0 0.0 1.1 0~%# estimate 1 0 0 0 0.0 1.0 0~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'froctomapFeedback)))
  "Returns full string definition for message of type 'froctomapFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%# update 0 0 0 0 0 0 0 ~%# recover 1 0 0 0 0 0 0~%# estimate 1 0 0 0 0.0 1.1 0~%# estimate 1 0 0 0 0.0 1.0 0~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <froctomapFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <froctomapFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'froctomapFeedback
))
