; Auto-generated. Do not edit!


(cl:in-package fremen-msg)


;//! \htmlinclude froctomapResult.msg.html

(cl:defclass <froctomapResult> (roslisp-msg-protocol:ros-message)
  ((sucessfull
    :reader sucessfull
    :initarg :sucessfull
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass froctomapResult (<froctomapResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <froctomapResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'froctomapResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fremen-msg:<froctomapResult> is deprecated: use fremen-msg:froctomapResult instead.")))

(cl:ensure-generic-function 'sucessfull-val :lambda-list '(m))
(cl:defmethod sucessfull-val ((m <froctomapResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fremen-msg:sucessfull-val is deprecated.  Use fremen-msg:sucessfull instead.")
  (sucessfull m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <froctomapResult>) ostream)
  "Serializes a message object of type '<froctomapResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'sucessfull) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <froctomapResult>) istream)
  "Deserializes a message object of type '<froctomapResult>"
    (cl:setf (cl:slot-value msg 'sucessfull) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<froctomapResult>)))
  "Returns string type for a message object of type '<froctomapResult>"
  "fremen/froctomapResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'froctomapResult)))
  "Returns string type for a message object of type 'froctomapResult"
  "fremen/froctomapResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<froctomapResult>)))
  "Returns md5sum for a message object of type '<froctomapResult>"
  "50a3c4d0f2f65351e7b4575a2e529624")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'froctomapResult)))
  "Returns md5sum for a message object of type 'froctomapResult"
  "50a3c4d0f2f65351e7b4575a2e529624")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<froctomapResult>)))
  "Returns full string definition for message of type '<froctomapResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool sucessfull~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'froctomapResult)))
  "Returns full string definition for message of type 'froctomapResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool sucessfull~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <froctomapResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <froctomapResult>))
  "Converts a ROS message object to a list"
  (cl:list 'froctomapResult
    (cl:cons ':sucessfull (sucessfull msg))
))
