; Auto-generated. Do not edit!


(cl:in-package fremen-msg)


;//! \htmlinclude informationFeedback.msg.html

(cl:defclass <informationFeedback> (roslisp-msg-protocol:ros-message)
  ((gain
    :reader gain
    :initarg :gain
    :type cl:float
    :initform 0.0))
)

(cl:defclass informationFeedback (<informationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <informationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'informationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fremen-msg:<informationFeedback> is deprecated: use fremen-msg:informationFeedback instead.")))

(cl:ensure-generic-function 'gain-val :lambda-list '(m))
(cl:defmethod gain-val ((m <informationFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fremen-msg:gain-val is deprecated.  Use fremen-msg:gain instead.")
  (gain m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <informationFeedback>) ostream)
  "Serializes a message object of type '<informationFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'gain))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <informationFeedback>) istream)
  "Deserializes a message object of type '<informationFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'gain) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<informationFeedback>)))
  "Returns string type for a message object of type '<informationFeedback>"
  "fremen/informationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'informationFeedback)))
  "Returns string type for a message object of type 'informationFeedback"
  "fremen/informationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<informationFeedback>)))
  "Returns md5sum for a message object of type '<informationFeedback>"
  "4d53ba7b6907d06399427297847c2640")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'informationFeedback)))
  "Returns md5sum for a message object of type 'informationFeedback"
  "4d53ba7b6907d06399427297847c2640")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<informationFeedback>)))
  "Returns full string definition for message of type '<informationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float64 gain~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'informationFeedback)))
  "Returns full string definition for message of type 'informationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float64 gain~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <informationFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <informationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'informationFeedback
    (cl:cons ':gain (gain msg))
))
